### ISSUE TITLE
TODO Verkle-Spec 

### ISSUE THREAD

**Issue by ControlCplusControlV** [crate-crypto/rust-verkle#63]
[**lib.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-spec/src/lib.rs#L8)
- [ ] - Specify the parts in the code where we assume VERKLE_WIDTH = 256
- [ ] - Expose type markers in verkle-trie, so we can ensure that none of them overlap
- [ ] - With the type markers in this crate. In particular, this crate uses 2, while verkle-trie uses 1 and 0

[**utils.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-spec/src/util.rs#L60)
- [ ] - This pads to 255*16, but we really only need it to be aligned
