### ISSUE TITLE
TODO Verkle-Trie (general-crate)

### ISSUE THREAD

**Issue by ControlCplusControlV** [crate-crypto/rust-verkle#64]
Top Level for the Verkle Trie Crate

[**commiter.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/committer.rs#L11)
- [ ] - We can make this &[Fr;256] since we have committed to 256, this would force the caller

[**config.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/config.rs#L20)
- [ ] - Refactor Functions to return VerkleError and consider API

[**from_to_bytes.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/from_to_bytes.rs)
- [ ] - Refactor to_bytes conversions to use fixed-length types

[**errors.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/errors.rs#L9)
- [ ] - Split out Error enum to contained grouped specific errors
