### ISSUE TITLE
TODO Verkle-Trie Database

### ISSUE THREAD

**Issue by ControlCplusControlV** [crate-crypto/rust-verkle#65]
[**database.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/database.rs)
- [ ] - We need a populate cache method that populates the cache from storage
- [ ] - Think of a better name than ReadOnlyHigherDb, WriteOnlyHigherDb
- [ ] - We could auto implement `update` methods which assert that there was a previous value they would just wrap the insert methods and check for `None`
- [ ] - We can probably combine `add_stem_as_branch_child` and `insert_branch` into a single method called `insert_branch_child`
- [ ] - Maybe we can return BranchChild, as the previous data could have been a stem or branch_meta then we can leave it upto the caller on how to deal with it on `insert_branch`
- [ ] - Add a range query for the default database in verkle_db (x2)

**default.rs**
- [ ] - Branch length check assumes that the cache is populated on startup from disk
- [ ] - Get Stem Children from cache assumes that the cache is populated on startup from disk

[**memory_db**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/database/memory_db.rs)
- [ ] - Maybe change `branch_table` to use BChild and also include the index in the key (Vec<u8>, u8)
- [ ] - `get_branch_child` could return the BranchChild instead and leave the caller to do what they want with it

[**meta.rs**](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/database/meta.rs#L74)
- [ ] - Explain where length check number comes from
- [ ] - Use more accurate error msg when length check fails
