### ISSUE TITLE
TODO Verkle Trie Trie

### ISSUE THREAD

**Issue by ControlCplusControlV** [crate-crypto/rust-verkle#67]
[trie.rs](https://github.com/crate-crypto/rust-verkle/blob/master/verkle-trie/src/trie.rs)
- [ ] - `root_commitment` This is needed for proofs, can we remove the root hash as the root?
- [ ] - In `new` We should have a way to populate the cache from the persistent db here. we first check if it is an new database and if it is not then we pull in all nodes on level 3 or lower. This way, if it is not in the cache, we know it is not in the key-value db either
- [ ] - `child_branch` this does not need to be optional
- [ ] - This is the only place here, where we require a get_leaf should we just allow users to update keys to be the same value and catch it maybe when we compute the delta? Rationale is that get_leaf only gets a single 32 bytes and database work in pages of ~4Kb
- [ ] - Update comments on this function on `Ins`
- [ ] - `flush` maybe make this private, and automatically flush after each insert. This will promote users to use insert(). If the amount of items in insert is too much, we will need to chop it up.  and flush multiple times
- [ ] - Clean up `path_difference`
- [ ] - `paths_from_relative` Is this hurting performance? If so can we rewrite it to be more efficient? Eagerly, we can use SmallVec32
- [ ] - Is this manual test needed, or can we add it as a consistency test? `insert_key1_val1_key2_val2`
